version: "3.8"

services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssword
      POSTGRES_USER: api_db_user
      POSTGRES_DB: api_db
    ports:
      - 5432:5432
  api:
    image: go-fiber-api:latest
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=api_db_user
      - DB_PASSWORD=P@ssword
      - REDIS_URL=redis://redis:6379/
      - PORT=3000
